import { clientUpdate } from "./status";
import { dateTime } from "./logic";
import { Badge, Button, PageHeading, Panel, Progress } from "./ui";

export function ClientStatus({ selected, analysis, setTab }) {
  const update = clientUpdate(selected, analysis);
  return <div className="page client-page">
    <PageHeading eyebrow="Client-safe communication" title="Service status update" text="This view shares impact, current work, and the next update without revealing internal risk scoring, team workload, or technical root-cause details." action={<Button variant="outline" onClick={() => setTab("incidents")}>Back to internal workbench</Button>}/>
    <div className="client-shell"><section className="client-letter"><header><div className="client-brand"><span>E</span><div><small>Elite Era Development L.L.C</small><strong>Service status update</strong></div></div><Badge tone={selected.status === "Resolved" ? "success" : selected.severity === "Critical" ? "danger" : "warning"}>{selected.status}</Badge></header><div className="client-intro"><p>Prepared for {selected.client}</p><h2>{selected.service}</h2><p>{update.summary}</p></div><div className="client-kpis"><article><span>Reported issue</span><strong>{selected.title}</strong><small>Opened {dateTime(selected.openedAt)}</small></article><article><span>Current activity</span><strong>{update.stage}</strong><small>Elite Era incident response is active</small></article><article><span>Client impact</span><strong>{selected.affectedUsers} users</strong><small>{selected.impact}</small></article></div><Panel eyebrow="What Elite Era is doing" title="Current recovery actions"><div className="client-actions-list">{selected.recovery.length ? selected.recovery.map((step) => <span key={step.id}>{step.done ? "✓" : "○"} {step.title}</span>) : <span>○ The recovery plan is being established.</span>}</div></Panel><div className="next-update"><strong>Next update</strong><p>{update.next}</p></div><footer>Made by Hira Khyzer · Elite Era Development L.L.C · #f4af00</footer></section><aside className="client-side"><Panel eyebrow="Incident timeline" title="Updates"><div className="client-timeline">{selected.updates.slice().reverse().map((item, index) => <article key={`${item.time}-${index}`}><i>{item.visibility === "Client" ? "✓" : "●"}</i><div><strong>{item.visibility === "Client" ? "Client update" : "Operational update"}</strong><small>{dateTime(item.time)}</small><p>{item.message}</p></div></article>)}</div></Panel><Panel eyebrow="Service information" title="Your support coverage"><div className="coverage"><span><b>Client tier</b><strong>{selected.tier}</strong></span><span><b>Severity</b><strong>{selected.severity}</strong></span><span><b>Status</b><strong>{selected.status}</strong></span><Progress value={analysis.completion} tone={analysis.completion >= 70 ? "green" : "gold"}/></div></Panel></aside></div>
  </div>;
}
