import { dateTime, percent } from "./logic";
import { Badge, Button, Metric, PageHeading, Panel, Progress } from "./ui";

const tone = (value) => value === "Safe" || value === "Met" ? "success" : value === "Watch" ? "warning" : "danger";

export function Dashboard({ state, summary, selected, selectedAnalysis, setTab, selectIncident, applyBestAssignment }) {
  const urgent = summary.analyses.slice().sort((a, b) => b.analysis.score - a.analysis.score)[0];
  return <div className="page">
    <PageHeading eyebrow="Elite Era Development L.L.C" title="Service reliability command center" text="Turn incident signals into accountable recovery work before SLA risk becomes a client-confidence problem." action={<Button onClick={() => setTab("incidents")}>Open incident workbench</Button>}/>
    <section className={`hero ${tone(urgent.analysis.breach)}`}><div><p>Highest service priority</p><h2>{urgent.incident.title}</h2><span>{urgent.incident.client} · {urgent.incident.tier} · {urgent.incident.severity} severity · opened {dateTime(urgent.incident.openedAt)}</span><div className="hero-actions"><Button onClick={() => { selectIncident(urgent.incident.id); setTab("incidents"); }}>Manage recovery →</Button><Button variant="outline" onClick={applyBestAssignment}>Apply best-fit owner</Button></div></div><div className="risk-orb"><div><b>{urgent.analysis.score}</b><small>breach risk</small><Badge tone={tone(urgent.analysis.breach)}>{urgent.analysis.breach}</Badge></div></div></section>
    <div className="metrics"><Metric label="Active incidents" value={summary.active.length} detail={`${summary.breached.length} breached or projected breached`} tone={summary.breached.length ? "danger" : "gold"} icon="!"/><Metric label="SLA at risk" value={summary.atRisk.length} detail="Requires incident-lead attention" tone={summary.atRisk.length ? "warning" : "success"} icon="◷"/><Metric label="Mean response" value={`${summary.mtta.toFixed(1)}h`} detail="Resolved incident response time" tone="blue" icon="↗"/><Metric label="Mean resolution" value={`${summary.mttr.toFixed(1)}h`} detail="Resolved incident duration" tone="ink" icon="◆"/></div>
    <div className="grid"><Panel eyebrow="Incident attention queue" title="Prioritize the client impact"><div className="attention">{summary.analyses.slice().sort((a,b)=>b.analysis.score-a.analysis.score).map(({ incident, analysis }) => <button key={incident.id} onClick={() => { selectIncident(incident.id); setTab("incidents"); }}><i className={tone(analysis.breach)}>●</i><div><strong>{incident.title}</strong><small>{incident.client} · {incident.status} · {analysis.score}/100 risk</small></div><Badge tone={tone(analysis.breach)}>{analysis.breach}</Badge><span>→</span></button>)}</div></Panel><Panel eyebrow="Selected incident" title="Live SLA position"><div className="selected-card"><div><Badge tone={tone(selectedAnalysis.breach)}>{selectedAnalysis.breach}</Badge><span>{selected.severity} · {selected.status}</span></div><h3>{selected.client}</h3><p>{selected.impact}</p><div className="sla-lines"><span>Response due <b>{dateTime(selectedAnalysis.sla.responseDue)}</b></span><span>Resolution due <b>{dateTime(selectedAnalysis.sla.resolutionDue)}</b></span><span>Recovery progress <b>{percent(selectedAnalysis.completion)}</b></span></div><Progress value={selectedAnalysis.completion} tone={selectedAnalysis.completion < 50 ? "gold" : "green"}/><Button variant="outline" onClick={() => setTab("incidents")}>Open incident</Button></div></Panel></div>
    <div className="grid"><Panel eyebrow="Client service health" title="Reliability by account"><div className="client-health">{summary.byClient.map((item) => <article key={item.client}><div><strong>{item.client}</strong><small>{item.active} active · {item.critical} critical</small></div><b>{item.breached ? "Needs recovery" : item.active ? "Active watch" : "Stable"}</b></article>)}</div></Panel><Panel eyebrow="Pattern detection" title="Repeat issue signal"><div className="repeat-list">{summary.repeat.length ? summary.repeat.map((item) => <article key={item.category}><i>↻</i><div><strong>{item.category}</strong><small>{item.count} incidents share this category. Consider a preventive engineering action.</small></div></article>) : <div className="empty"><i>✓</i><strong>No repeat-pattern alert</strong><p>Current issue categories do not yet indicate a recurring incident pattern.</p></div>}</div></Panel></div>
  </div>;
}
