import { dateTime, percent } from "./logic";
import { Badge, Button, Metric, PageHeading, Panel } from "./ui";

const tone = (value) => value === "Safe" || value === "Met" ? "success" : value === "Watch" ? "warning" : "danger";

export function Reports({ state, summary, selected, analysis, saveReport, removeReport, exportText, exportJson, resetWorkspace }) {
  return <div className="page">
    <PageHeading eyebrow="Reliability governance" title="Service reports and prevention records" text="Save the incident position before a client review, escalation meeting, root-cause review, or prevention decision." action={<Button onClick={saveReport}>Save incident snapshot</Button>}/>
    <div className="metrics"><Metric label="SLA position" value={analysis.breach} detail={`${analysis.score}/100 breach risk`} tone={tone(analysis.breach)} icon="◆"/><Metric label="Client impact" value={`${analysis.impact}/100`} detail={`${selected.affectedUsers} affected users`} tone={analysis.impact >= 70 ? "danger" : "warning"} icon="!"/><Metric label="Recovery progress" value={percent(analysis.completion)} detail={`${selected.recovery.filter((item)=>item.done).length}/${selected.recovery.length} steps complete`} tone={analysis.completion >= 70 ? "success" : "gold"} icon="✓"/><Metric label="Active incidents" value={summary.active.length} detail={`${summary.atRisk.length} require extra attention`} tone={summary.atRisk.length ? "warning" : "blue"} icon="◷"/></div>
    <div className="report-grid"><Panel eyebrow="Export package" title="Share incident evidence"><div className="export-actions"><Button onClick={exportText}>Download TXT report</Button><Button variant="outline" onClick={exportJson}>Download JSON</Button><Button variant="outline" onClick={() => window.print()}>Print / Save as PDF</Button></div><div className="report-preview"><strong>{selected.title}</strong><span>{selected.client} · {selected.tier}</span><span>Response deadline: {dateTime(analysis.sla.responseDue)}</span><span>Resolution deadline: {dateTime(analysis.sla.resolutionDue)}</span><span>Root cause: {selected.rootCause || "Pending review"}</span></div></Panel><Panel eyebrow="Prototype workspace" title="Data control"><p className="report-copy">All data is stored only in this browser until a production database is connected. Use exports for handoff or records.</p><Button variant="outline" onClick={resetWorkspace}>Reset demo workspace</Button><div className="brand-rows"><span>Made by</span><b>Hira Khyzer</b><span>Company</span><b>Elite Era Development L.L.C</b><span>Brand color</span><b>#f4af00</b></div></Panel></div>
    <Panel eyebrow="Saved incident snapshots" title="Reliability report library" text="Keep a historical record of incident risk, owner, recovery, and post-incident decisions.">{state.savedReports.length ? <div className="report-list"><div className="report-head"><span>Incident</span><span>Client</span><span>SLA</span><span>Risk</span><span>Saved</span><span/></div>{state.savedReports.map((report) => <div className="report-row" key={report.id}><div><strong>{report.title}</strong><small>{report.status}</small></div><span>{report.client}</span><Badge tone={tone(report.breach)}>{report.breach}</Badge><span>{report.score}/100</span><span>{report.createdAt}</span><button onClick={() => removeReport(report.id)}>Remove</button></div>)}</div> : <div className="empty"><i>▤</i><strong>No saved snapshots</strong><p>Save the current incident view before changing the recovery strategy or closing the case.</p></div>}</Panel>
    <Panel eyebrow="Service performance" title="Reliability overview"><div className="performance"><article><span>Mean time to acknowledge</span><b>{summary.mtta.toFixed(1)} hours</b></article><article><span>Mean time to resolve</span><b>{summary.mttr.toFixed(1)} hours</b></article><article><span>Repeated issue categories</span><b>{summary.repeat.length}</b></article><article><span>Breached incidents</span><b>{summary.breached.length}</b></article></div></Panel>
  </div>;
}
