import { useMemo, useState } from "react";
import { INCIDENT_STATUSES, SEVERITIES, SKILLS } from "./data";
import { assignmentOptions, recoveryGuidance } from "./analytics";
import { dateTime, incidentAnalysis, percent } from "./logic";
import { Avatar, Badge, Button, PageHeading, Panel, Progress } from "./ui";

const tone = (value) => value === "Safe" || value === "Met" ? "success" : value === "Watch" ? "warning" : "danger";

export function Workbench({ state, selected, selectedAnalysis, selectIncident, patchIncident, toggleRecovery, addClientUpdate, setTab }) {
  const [updateText, setUpdateText] = useState("");
  const [showNew, setShowNew] = useState(false);
  const [draft, setDraft] = useState({ title: "", client: "", tier: "Gold", service: "", severity: "Medium", impact: "", affectedUsers: 1, skills: [], category: "General" });
  const options = useMemo(() => assignmentOptions(selected, state.engineers), [selected, state.engineers]);
  const guidance = useMemo(() => recoveryGuidance(selected, selectedAnalysis), [selected, selectedAnalysis]);
  const toggleSkill = (skill) => setDraft((current) => ({ ...current, skills: current.skills.includes(skill) ? current.skills.filter((item) => item !== skill) : [...current.skills, skill] }));
  function submitUpdate(event) { event.preventDefault(); if (!updateText.trim()) return; addClientUpdate(selected.id, updateText.trim()); setUpdateText(""); }
  function submitIncident(event) { event.preventDefault(); if (!draft.title.trim() || !draft.client.trim() || !draft.skills.length) return; patchIncident("new", { ...draft, id: `inc-${Date.now()}`, status: "New", openedAt: new Date().toISOString(), firstResponseAt: "", resolvedAt: "", assigneeId: "", updates: [], recovery: [], rootCause: "", prevention: "" }); setShowNew(false); }
  return <div className="page">
    <PageHeading eyebrow="Incident workbench" title="Manage incident recovery" text="Assign the right technical owner, progress recovery actions, maintain client-safe updates, and complete the root-cause record before closure." action={<Button onClick={() => setShowNew((value) => !value)}>{showNew ? "Close incident form" : "Log new incident"}</Button>}/>
    {showNew && <Panel eyebrow="New incident intake" title="Create a tracked service incident"><form className="incident-form" onSubmit={submitIncident}><label>Incident title<input required value={draft.title} onChange={(event) => setDraft((current) => ({ ...current, title: event.target.value }))} placeholder="e.g. Client report generation failure"/></label><label>Client<input required value={draft.client} onChange={(event) => setDraft((current) => ({ ...current, client: event.target.value }))} placeholder="Client company"/></label><label>Tier<select value={draft.tier} onChange={(event) => setDraft((current) => ({ ...current, tier: event.target.value }))}><option>Platinum</option><option>Gold</option><option>Standard</option></select></label><label>Severity<select value={draft.severity} onChange={(event) => setDraft((current) => ({ ...current, severity: event.target.value }))}>{SEVERITIES.map((item) => <option key={item}>{item}</option>)}</select></label><label>Affected users<input type="number" min="1" value={draft.affectedUsers} onChange={(event) => setDraft((current) => ({ ...current, affectedUsers: Number(event.target.value) || 1 }))}/></label><label>Category<input value={draft.category} onChange={(event) => setDraft((current) => ({ ...current, category: event.target.value }))}/></label><label className="wide">Service<input value={draft.service} onChange={(event) => setDraft((current) => ({ ...current, service: event.target.value }))} placeholder="Affected Elite Era service"/></label><label className="wide">Client impact<textarea rows="2" value={draft.impact} onChange={(event) => setDraft((current) => ({ ...current, impact: event.target.value }))} placeholder="Describe what the client cannot do."/></label><div className="wide"><span className="label">Required skills</span><div className="skill-picker">{SKILLS.map((skill) => <button type="button" key={skill} className={draft.skills.includes(skill) ? "selected" : ""} onClick={() => toggleSkill(skill)}>{draft.skills.includes(skill) ? "✓ " : "+ "}{skill}</button>)}</div></div><div className="form-actions"><Button type="submit">Create incident</Button><Button variant="outline" onClick={() => setShowNew(false)}>Cancel</Button></div></form></Panel>}
    <div className="workbench"><Panel eyebrow="Incident queue" title="Select a case"><div className="incident-list">{state.incidents.slice().sort((a,b)=>incidentAnalysis(b).score-incidentAnalysis(a).score).map((incident) => { const analysis = incidentAnalysis(incident); return <button key={incident.id} className={incident.id === selected.id ? "selected" : ""} onClick={() => selectIncident(incident.id)}><i className={tone(analysis.breach)}>●</i><div><strong>{incident.title}</strong><small>{incident.client} · {incident.severity} · {analysis.score}/100 risk</small></div><Badge tone={tone(analysis.breach)}>{analysis.breach}</Badge></button>; })}</div></Panel><div className="incident-detail"><Panel eyebrow="Live incident" title={selected.title}><div className="detail-top"><div><Badge tone={tone(selectedAnalysis.breach)}>{selectedAnalysis.breach}</Badge><Badge tone={selected.severity === "Critical" ? "danger" : selected.severity === "High" ? "warning" : "neutral"}>{selected.severity}</Badge></div><span>{selected.client} · {selected.tier} · opened {dateTime(selected.openedAt)}</span></div><p className="impact-copy">{selected.impact}</p><div className="control-grid"><label>Status<select value={selected.status} onChange={(event) => patchIncident(selected.id, { status: event.target.value, resolvedAt: event.target.value === "Resolved" && !selected.resolvedAt ? new Date().toISOString() : selected.resolvedAt })}>{INCIDENT_STATUSES.map((item) => <option key={item}>{item}</option>)}</select></label><label>Technical owner<select value={selected.assigneeId} onChange={(event) => patchIncident(selected.id, { assigneeId: event.target.value })}><option value="">Auto-assign recommended owner</option>{state.engineers.map((engineer) => <option key={engineer.id} value={engineer.id}>{engineer.name} · {engineer.role}</option>)}</select></label></div><div className="sla-card"><span>Response deadline <b>{dateTime(selectedAnalysis.sla.responseDue)}</b></span><span>Resolution deadline <b>{dateTime(selectedAnalysis.sla.resolutionDue)}</b></span><span>Client impact <b>{selectedAnalysis.impact}/100</b></span><span>Recovery complete <b>{percent(selectedAnalysis.completion)}</b></span></div><Progress value={selectedAnalysis.completion} tone={selectedAnalysis.completion >= 70 ? "green" : "gold"}/></Panel>
      <div className="detail-grid"><Panel eyebrow="Skill-based assignment" title="Recommended incident owner"><div className="assignment-list">{options.map((engineer, index) => <article key={engineer.id}><Avatar initials={engineer.initials}/><div><strong>{engineer.name}</strong><small>{engineer.role} · {Math.round(engineer.match * 100)}% skill fit · {Math.round(engineer.free * 100)}% free capacity</small></div><b>{engineer.score}</b>{index === 0 && <Button onClick={() => patchIncident(selected.id, { assigneeId: engineer.id })}>Assign</Button>}</article>)}</div></Panel><Panel eyebrow="Recovery checklist" title="Current mitigation work"><div className="recovery-list">{selected.recovery.length ? selected.recovery.map((step) => <article key={step.id}><button className={step.done ? "done" : ""} onClick={() => toggleRecovery(selected.id, step.id)}>{step.done ? "✓" : "○"}</button><div><strong>{step.title}</strong><small>{step.owner}</small></div></article>) : <div className="empty"><i>○</i><strong>No recovery steps yet</strong><p>Add a recovery checklist before work begins.</p></div>}</div></Panel></div>
      <div className="detail-grid"><Panel eyebrow="Recovery guidance" title="Recommended next moves"><div className="guidance">{guidance.map((item) => <article key={item.title}><i>!</i><div><strong>{item.title}</strong><p>{item.detail}</p></div></article>)}</div></Panel><Panel eyebrow="Client update log" title="Share clear status"><form className="update-form" onSubmit={submitUpdate}><textarea rows="3" value={updateText} onChange={(event) => setUpdateText(event.target.value)} placeholder="Write a factual, client-safe progress update."/><Button type="submit">Add client update</Button></form><div className="update-list">{selected.updates.slice().reverse().map((item, index) => <article key={`${item.time}-${index}`}><div><Badge tone={item.visibility === "Client" ? "success" : "neutral"}>{item.visibility}</Badge><small>{dateTime(item.time)}</small></div><p>{item.message}</p></article>)}</div></Panel></div>
      <Panel eyebrow="Post-incident review" title="Root cause and prevention"><div className="post-grid"><label>Root cause<textarea rows="4" value={selected.rootCause} onChange={(event) => patchIncident(selected.id, { rootCause: event.target.value })} placeholder="What technical or process condition caused this incident?"/></label><label>Prevention action<textarea rows="4" value={selected.prevention} onChange={(event) => patchIncident(selected.id, { prevention: event.target.value })} placeholder="What specific control will reduce repeat risk?"/></label></div></Panel>
    </div></div>
  </div>;
}
